(function(){
    const scopeRoot = (typeof root_element !== 'undefined' && root_element) ? root_element : document;
    let idx = { a1: 1, a2: 1 };

    function init(){ buildTabs(); buildA1(); buildA2(); attachBlockers(); }
    function buildTabs(){ const c=scopeRoot.querySelector('.lime-container'); if(!c) return; const btns=c.querySelectorAll('.tab-btn'); const tabs={ 'approach-1':c.querySelector('#approach-1-tab'), 'approach-2':c.querySelector('#approach-2-tab') }; btns.forEach(b=> b.addEventListener('click', ()=>{ btns.forEach(x=>x.classList.remove('active')); b.classList.add('active'); Object.values(tabs).forEach(t=>t.classList.remove('active')); const id=b.dataset.tab; if(tabs[id]) tabs[id].classList.add('active'); })); }

    async function getUnits(){ try { const userResp=await frappe.call({ method:'frappe.client.get', args:{ doctype:'User', name: frappe.session && frappe.session.user ? frappe.session.user : 'Administrator' } }); const company=(userResp.message&&userResp.message.company)||null; if(!company) return []; const r=await frappe.call({ method:'frappe.client.get_list', args:{ doctype:'Units', fields:['name'], filters:{ company }, limit_page_length:200 } }); return (r.message||[]).map(u=>u.name); } catch(e){ return []; } }
    function unitOptions(units){ return units.map(u=>`<option value="${u}">${u}</option>`).join(''); }
    function today(){ return new Date().toISOString().split('T')[0]; }

    async function fetchDefaults(){
        try { const r=await frappe.call({ method:'frappe.client.get_list', args:{ doctype:'Lime Defaults', fields:['*'], limit_page_length:500 } }); return r.message||[]; } catch(e){ return []; }
    }
    function getLimeTypeDefaults(all, type){ const recs=all.filter(d=> d.default_type==='lime_type' && d.lime_type===type); if(!recs.length) return null; const d=recs[0]; return { stoich: fnum(d.stoichiometric_ratio), cao_dev: fnum(d.cao_ratio_developed), cao_deving: fnum(d.cao_ratio_developing), cao_single: fnum(d.cao_ratio_single) }; }
    function getGlobalDefaults(all){ const g=all.find(d=> d.default_type==='global'); return g? { hydrated_prop: fnum(g.hydrated_proportion_default), hydrated_water: fnum(g.hydrated_water_content_default), lkd_factor: fnum(g.lkd_correction_default), lkd_wf: fnum(g.lkd_weight_fraction_default) } : { hydrated_prop:0.1, hydrated_water:0.28, lkd_factor:1.02, lkd_wf:0.9 }; }
    function getCarbonateEF(all, carbonate){ const r=all.find(d=> d.default_type==='carbonate' && d.carbonate===carbonate); return r? fnum(r.emission_factor_tco2_per_t): 0; }

    async function buildA1(){ const tbody=scopeRoot.querySelector('#approach1Body'); if(!tbody) return; const units=await getUnits(); const dfl=await fetchDefaults(); const row=document.createElement('tr'); row.className='data-entry-row'; row.innerHTML = `<td>${idx.a1}</td><td><input type=\"date\" class=\"form-control date\" value=\"${today()}\"></td><td><select class=\"form-control unit\"><option value=\"\">-- Unit --</option>${unitOptions(units)}</select></td><td><select class=\"form-control ltype\"><option value=\"\">-- Type --</option><option>High-calcium</option><option>Dolomitic</option><option>Hydraulic</option></select></td><td><input type=\"number\" class=\"form-control prod\" step=\"0.01\"></td><td><div class=\"country\"><label><input type=\"radio\" name=\"country_type\" value=\"developed\" checked> Developed</label> <label><input type=\"radio\" name=\"country_type\" value=\"developing\"> Developing</label></div></td><td><span class=\"calculated-value cao\">0.00</span></td><td><span class=\"calculated-value stoich\">0.0000</span></td><td><span class=\"calculated-value hprop\">0.0000</span></td><td><span class=\"calculated-value hwater\">0.0000</span></td><td><span class=\"calculated-value lkd\">0.0000</span></td><td><span class=\"calculated-value em\">0.00</span></td><td><button class=\"btn btn-success add\">Add</button></td>`; tbody.appendChild(row);
        const calc=()=>{ const prod=fnum(val(row,'.prod')); const stoich=fnum(row.querySelector('.stoich').textContent); const cao=fnum(row.querySelector('.cao').textContent); const hp=fnum(row.querySelector('.hprop').textContent); const hw=fnum(row.querySelector('.hwater').textContent); const lkd=fnum(row.querySelector('.lkd').textContent); const base=prod*stoich*cao; const corr=base*(1 - (hp*hw)); const em=corr*lkd; row.querySelector('.em').textContent=(isFinite(em)?em:0).toFixed(2); };
        const applyType=()=>{ const type=val(row,'.ltype'); const gd=getGlobalDefaults(dfl); if(!type){ row.querySelector('.cao').textContent='0.00'; row.querySelector('.stoich').textContent='0.0000'; row.querySelector('.hprop').textContent='0.0000'; row.querySelector('.hwater').textContent='0.0000'; row.querySelector('.lkd').textContent='0.0000'; calc(); return; } const lt=getLimeTypeDefaults(dfl, type); if(!lt){ row.querySelector('.cao').textContent='0.00'; return; } const ctyp=row.querySelector('input[name="country_type"]:checked').value; const cao = type==='Dolomitic' ? (ctyp==='developed'? lt.cao_dev : lt.cao_deving) : lt.cao_single; row.querySelector('.cao').textContent=(cao||0).toFixed(3); row.querySelector('.stoich').textContent=(lt.stoich||0).toFixed(4); row.querySelector('.hprop').textContent=(gd.hydrated_prop||0).toFixed(4); row.querySelector('.hwater').textContent=(gd.hydrated_water||0).toFixed(4); row.querySelector('.lkd').textContent=(gd.lkd_factor||0).toFixed(4); calc(); };
        row.querySelector('.ltype').addEventListener('change', applyType); row.querySelectorAll('input[name="country_type"]').forEach(r=> r.addEventListener('change', applyType)); row.querySelectorAll('input.prod').forEach(i=>{ i.addEventListener('input', calc); i.addEventListener('change', calc); }); applyType(); row.querySelector('.add').addEventListener('click', (e)=>{ e.preventDefault(); addA1(row); });
    }
    function addA1(entry){ const tbody=entry.parentElement; const tr=document.createElement('tr'); tr.className='data-display-row'; const d=val(entry,'.date'); const unit=val(entry,'.unit'); const type=val(entry,'.ltype'); const ctyp=entry.querySelector('input[name="country_type"]:checked').value; const cao=entry.querySelector('.cao').textContent; const stoich=entry.querySelector('.stoich').textContent; const hprop=entry.querySelector('.hprop').textContent; const hwater=entry.querySelector('.hwater').textContent; const lkd=entry.querySelector('.lkd').textContent; tr.innerHTML=`<td>${idx.a1}</td><td>${format(d)}</td><td>${unit||'-'}</td><td>${type||'-'}</td><td>${val(entry,'.prod')}</td><td>${ctyp}</td><td>${cao}</td><td>${stoich}</td><td>${hprop}</td><td>${hwater}</td><td>${lkd}</td><td>${entry.querySelector('.em').textContent}</td><td><button class='btn btn-danger del'>Delete</button></td>`; tbody.insertBefore(tr, entry.nextSibling); save('Lime Emissions Approach 1',{ date:d, unit, lime_type:type, country_type:ctyp, production_t:fnum(val(entry,'.prod')), cao_ratio:fnum(cao), stoichiometric_ratio:fnum(stoich), hydrated_proportion:fnum(hprop), hydrated_water_content:fnum(hwater), lkd_factor:fnum(lkd), co2_emissions_t:fnum(entry.querySelector('.em').textContent) }, (dn)=> tr.setAttribute('data-doc', dn||'')); idx.a1+=1; entry.querySelector('td:first-child').textContent=idx.a1; clearA1(entry); tr.querySelector('.del').addEventListener('click', ()=> delRow(tr,'Lime Emissions Approach 1')); }
    function clearA1(r){ r.querySelectorAll('input').forEach(i=>{ if(i.type==='date'){ i.value=today(); } else if(i.type==='radio'){ if(i.value==='developed') i.checked=true; } else { i.value=''; } }); r.querySelector('.cao').textContent='0.00'; r.querySelector('.stoich').textContent='0.0000'; r.querySelector('.hprop').textContent='0.0000'; r.querySelector('.hwater').textContent='0.0000'; r.querySelector('.lkd').textContent='0.0000'; r.querySelector('.em').textContent='0.00'; }

    async function buildA2(){ const tbody=scopeRoot.querySelector('#approach2Body'); if(!tbody) return; const units=await getUnits(); const dfl=await fetchDefaults(); const row=document.createElement('tr'); row.className='data-entry-row'; row.innerHTML=`<td>${idx.a2}</td><td><input type=\"date\" class=\"form-control date\" value=\"${today()}\"></td><td><select class=\"form-control unit\"><option value=\"\">-- Unit --</option>${unitOptions(units)}</select></td><td><select class=\"form-control carb\"><option value=\"\">-- Carbonate --</option><option>CaCO3</option><option>MgCO3</option><option>CaMg(CO3)2</option><option>FeCO3</option><option>Ca(Fe,Mg,Mn)(CO3)2</option><option>Na2CO3</option><option>MnCO3</option></select></td><td><span class=\"calculated-value ef\">0.0000</span></td><td><input type=\"number\" class=\"form-control amt\" step=\"0.01\"></td><td><input type=\"number\" class=\"form-control frac_c\" step=\"0.0001\" value=\"1.0\"></td><td><input type=\"number\" class=\"form-control lkd_amt\" step=\"0.01\"></td><td><input type=\"number\" class=\"form-control lkd_wf\" step=\"0.0001\"></td><td><input type=\"number\" class=\"form-control frac_lkd\" step=\"0.0001\" value=\"1.0\"></td><td><span class=\"calculated-value em\">0.00</span></td><td><button class=\"btn btn-success add\">Add</button></td>`; tbody.appendChild(row); const applyCarb=()=>{ const carb=val(row,'.carb'); let ef=getCarbonateEF(dfl, carb); if(carb==='Ca(Fe,Mg,Mn)(CO3)2') ef=0.44; row.querySelector('.ef').textContent=(ef||0).toFixed(4); calc(); }; const calc=()=>{ const ef=fnum(row.querySelector('.ef').textContent); const amt=fnum(val(row,'.amt')); const fc=fnum(val(row,'.frac_c'))||1; const lkd_amt=fnum(val(row,'.lkd_amt')); const lkd_wf=fnum(val(row,'.lkd_wf')); const fl=fnum(val(row,'.frac_lkd'))||1; const primary=ef*amt*fc; const lkd_adj=lkd_amt*lkd_wf*(1-fl)*ef; const em=primary-lkd_adj; row.querySelector('.em').textContent=em.toFixed(2); }; row.querySelector('.carb').addEventListener('change', applyCarb); row.querySelectorAll('input').forEach(i=>{ i.addEventListener('input', calc); i.addEventListener('change', calc); }); row.querySelector('.add').addEventListener('click', (e)=>{ e.preventDefault(); addA2(row); }); } 
    function addA2(entry){ const tbody=entry.parentElement; const tr=document.createElement('tr'); tr.className='data-display-row'; const d=val(entry,'.date'); const unit=val(entry,'.unit'); const ef=entry.querySelector('.ef').textContent; tr.innerHTML=`<td>${idx.a2}</td><td>${format(d)}</td><td>${unit||'-'}</td><td>${val(entry,'.carb')}</td><td>${ef}</td><td>${val(entry,'.amt')}</td><td>${val(entry,'.frac_c')}</td><td>${val(entry,'.lkd_amt')}</td><td>${val(entry,'.lkd_wf')}</td><td>${val(entry,'.frac_lkd')}</td><td>${entry.querySelector('.em').textContent}</td><td><button class='btn btn-danger del'>Delete</button></td>`; tbody.insertBefore(tr, entry.nextSibling); save('Lime Emissions Approach 2',{ date:d, unit, carbonate:val(entry,'.carb'), emission_factor_tco2_per_t:fnum(ef), amount_t:fnum(val(entry,'.amt')), fraction_calcination_carbonate:fnum(val(entry,'.frac_c')), lkd_amount_t:fnum(val(entry,'.lkd_amt')), lkd_weight_fraction:fnum(val(entry,'.lkd_wf')), fraction_calcination_lkd:fnum(val(entry,'.frac_lkd')), co2_emissions_t:fnum(entry.querySelector('.em').textContent) }, (dn)=> tr.setAttribute('data-doc', dn||'')); idx.a2+=1; entry.querySelector('td:first-child').textContent=idx.a2; clearA2(entry); tr.querySelector('.del').addEventListener('click', ()=> delRow(tr,'Lime Emissions Approach 2')); }
    function clearA2(r){ r.querySelectorAll('input').forEach(i=>{ if(i.type==='date'){ i.value=today(); } else if(i.classList.contains('frac_c') || i.classList.contains('frac_lkd')){ i.value='1.0'; } else { i.value=''; } }); r.querySelector('.ef').textContent='0.0000'; r.querySelector('.em').textContent='0.00'; }

    function save(dt, data, cb){ frappe.call({ method:'frappe.client.insert', args:{ doc:{ doctype: dt, ...data } }, callback:(r)=> cb && cb(r.message && r.message.name), error:(err)=> { console.error('Save error', dt, err); cb && cb(null); } }); }
    function delRow(tr, dt){ const dn=tr.getAttribute('data-doc'); if(!dn){ tr.remove(); return; } frappe.call({ method:'frappe.client.delete', args:{ doctype: dt, name: dn }, callback: ()=> tr.remove(), error: ()=> tr.remove() }); }
    function fnum(v){ const n=parseFloat(v); return isFinite(n)?n:0; }
    function val(s,sel,def=''){ const el=s.querySelector(sel); if(!el) return def; if(el.tagName==='INPUT'||el.tagName==='SELECT') return el.type==='number'? (parseFloat(el.value)||0).toString(): (el.value||def); return el.value||def; }
    function format(d){ if(!d) return '-'; return new Date(d).toLocaleDateString(); }
    function attachBlockers(){ const container=scopeRoot.querySelector('.lime-container'); if(!container) return; const h=(e)=>{ if(!container.contains(e.target)) return; e.stopPropagation(); if((e.ctrlKey||e.metaKey)|| e.key==='/' || e.key==='?'){ e.preventDefault(); } }; ['keydown','keypress','keyup'].forEach(ev=> document.addEventListener(ev,h,true)); }

    if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', ()=> init()); } else { init(); }
})();


