# CO2 Imports & Exports DocType Creation
# Run this in Frappe console: bench --site localhost console

import frappe

def ensure_doctype(name, fields, module_hint="Climoro Onboarding"):
    module_name = module_hint if frappe.db.exists("Module Def", module_hint) else "Core"
    if not frappe.db.exists("DocType", name):
        doc = frappe.new_doc("DocType")
        doc.name = name
        doc.module = module_name
        doc.custom = 1
        doc.editable_grid = 1
        doc.track_changes = 1
        for f in fields:
            doc.append("fields", f)
        doc.append("permissions", {"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1})
        doc.append("permissions", {"role": "All", "read": 1, "write": 1, "create": 1})
        doc.insert(ignore_permissions=True)
        frappe.db.commit()
    try:
        frappe.db.updatedb(name)
    except Exception:
        pass

print("\n🚀 Ensuring CO2 Imports & Exports DocType...")
try:
    ensure_doctype(
        "CO2 Imports and Exports",
        [
            {"fieldname": "date", "label": "Date", "fieldtype": "Date", "reqd": 1, "in_list_view": 1, "in_standard_filter": 1},
            {"fieldname": "form_type", "label": "Form Type", "fieldtype": "Select", "options": "CO2 Imports\nCO2 Exports to PCC", "reqd": 1, "in_list_view": 1},
            {"fieldname": "total_co2_imported", "label": "Total fossil CO2 imported to mill (metric tons CO2/year)", "fieldtype": "Float", "default": 0, "in_list_view": 1},
            {"fieldname": "total_co2_generated", "label": "Total CO2 generated by burning fossil fuel (metric tons CO2/year)", "fieldtype": "Float", "default": 0, "in_list_view": 1},
            {"fieldname": "fraction_sent_to_pcc", "label": "Fraction of gas sent to PCC plant", "fieldtype": "Float", "default": 0, "in_list_view": 1},
            {"fieldname": "fossil_co2_exports", "label": "Fossil CO2 Exports to PCC plant (metric tons CO2/year)", "fieldtype": "Float", "read_only": 1, "default": 0, "in_list_view": 1},
            {"fieldname": "biomass_co2_approximation", "label": "Biomass CO2 approximation (2x fossil CO2)", "fieldtype": "Float", "read_only": 1, "default": 0, "in_list_view": 1},
            {"fieldname": "notes", "label": "Notes", "fieldtype": "Text", "in_list_view": 1},
        ],
    )
    print("✅ CO2 Imports & Exports DocType ensured.")
except Exception as e:
    print("❌ Error ensuring CO2 Imports & Exports DocType:", str(e))
